# https://taskfile.dev

version: "3"

vars:
  PROJECT: termo
  ENTRY: src/teRMo.py
  APP: teRMo

tasks:
  default:
    desc: run flask cli
    dir: src/
    cmds:
      - mamba run --live-stream -n {{.PROJECT}} python -m {{.PROJECT}}.cli {{.CLI_ARGS}}

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true

  export:
    desc: export env
    cmds:
      - mamba env export --no-builds -n {{.PROJECT}} > environment.yml

  build:
    desc: build app
    cmds:
      - mamba run --live-stream -n {{.PROJECT}} python -m nuitka {{.ENTRY}}

  install:
    desc: install app
    cmds:
      - killall {{.APP}} || true
      - rm -rf /Applications/{{.APP}}.app
      - mv {{.APP}}.app /Applications
